# Generated by Django 5.1.7 on 2025-03-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_products_sizes_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
