# Generated by Django 5.1.7 on 2025-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.TextField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
