# Generated by Django 5.1.7 on 2025-04-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
