# Generated by Django 5.1.7 on 2025-04-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
    ]
