# Generated by Django 5.1.7 on 2025-04-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_products_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
    ]
