# Generated by Django 5.1.7 on 2025-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_products_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='S',
            field=models.BooleanField(default=False),
        ),
    ]
