# Generated by Django 5.1.7 on 2025-04-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_products_s_remove_products_stock_productsize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
